CREATE TABLE IF NOT EXISTS person (
  Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
  document_national INTEGER ,
  type_document VARCHAR(50) ,
  age INTEGER ,
  name VARCHAR(100) ,
  gender VARCHAR(20)
  );

CREATE TABLE IF NOT EXISTS address (
  Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
  street VARCHAR(20) ,
  city VARCHAR(20) ,
  country VARCHAR (20) ,
  postal_code INTEGER,
  person_id INTEGER
);

--ALTER TABLE address
--  ADD CONSTRAINT address_person_fk
--  FOREIGN KEY (person_id)
--  REFERENCES person(id);

CREATE TABLE IF NOT EXISTS contact (
  id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
  mail VARCHAR(50) ,
  number_call VARCHAR(50) ,
  person_id INTEGER
);

--ALTER TABLE  contact
--  ADD CONSTRAINT contact_person_fk
--  FOREIGN KEY (person_id)
--  REFERENCES person(id);
